CREATE SCHEMA IF NOT EXISTS touristguide3;

SET SCHEMA touristguide3;

DROP TABLE IF EXISTS TOURISTATTRACTION;

CREATE TABLE TOURISTATTRACTION (
                                   TOURISTID INTEGER NOT NULL AUTO_INCREMENT,
                                   ANAME VARCHAR(50),
                                   ADESCRIPTION VARCHAR(250),
                                   PRIMARY KEY (TOURISTID),
                                   UNIQUE (ANAME)
);

DROP TABLE IF EXISTS TAG;

CREATE TABLE TAG (
                     TAGSID INTEGER NOT NULL AUTO_INCREMENT,
                     TDESCRIPTION VARCHAR(50),
                     PRIMARY KEY (TAGSID)
);

DROP TABLE IF EXISTS TOURISTATTACTION_TAGS;

CREATE TABLE TOURISTATTACTION_TAGS (
                                                      TAGSID INTEGER,
                                                      TOURISTID INTEGER,
                                                      FOREIGN KEY (TAGSID) REFERENCES TAG(TAGSID),
                                                      FOREIGN KEY (TOURISTID) REFERENCES TOURISTATTRACTION(TOURISTID)
);

-- Inserting data into the TOURISTATTRACTION table
INSERT INTO TOURISTATTRACTION (ANAME, ADESCRIPTION) VALUES ('H2 Brøndby Stadion', 'God stemning og gode pølser');
INSERT INTO TOURISTATTRACTION (ANAME, ADESCRIPTION) VALUES ('H2 Nature Energy Park', 'OBs Stadion. God pølsemix. Forvent sure fans');
INSERT INTO TOURISTATTRACTION (ANAME, ADESCRIPTION) VALUES ('H2 Parken', 'Største danske fodboldstadion, Tag kun derind når Danmarks landshold spiller');
INSERT INTO TOURISTATTRACTION (ANAME, ADESCRIPTION) VALUES ('H2 Right to dream park', 'Ingen fans, men okay fodbold. DÅRLIG BANE');

-- Inserting data into the TAG table
INSERT INTO TAG (TDESCRIPTION) VALUES ('Billige øl');
INSERT INTO TAG (TDESCRIPTION) VALUES ('Gode Pølser');
INSERT INTO TAG (TDESCRIPTION) VALUES ('Sure Fans');
INSERT INTO TAG (TDESCRIPTION) VALUES ('Dårlig Bane');
INSERT INTO TAG (TDESCRIPTION) VALUES ('God Bane');
INSERT INTO TAG (TDESCRIPTION) VALUES ('Flot Stadion');

-- Inserting data into the TOURISTATTACTION_TAGS table
INSERT INTO TOURISTATTACTION_TAGS (TAGSID, TOURISTID) VALUES (2, 4);
INSERT INTO TOURISTATTACTION_TAGS (TAGSID, TOURISTID) VALUES (3, 4);
INSERT INTO TOURISTATTACTION_TAGS (TAGSID, TOURISTID) VALUES (5, 3);
INSERT INTO TOURISTATTACTION_TAGS (TAGSID, TOURISTID) VALUES (6, 3);
INSERT INTO TOURISTATTACTION_TAGS (TAGSID, TOURISTID) VALUES (4, 1);
INSERT INTO TOURISTATTACTION_TAGS (TAGSID, TOURISTID) VALUES (3, 1);
INSERT INTO TOURISTATTACTION_TAGS (TAGSID, TOURISTID) VALUES (4, 2);
INSERT INTO TOURISTATTACTION_TAGS (TAGSID, TOURISTID) VALUES (6, 2);
